db {
  provider = cassandra
  cassandra {
    cluster = ["cassandra:9042"]
    keyspace = thehive
    ssl = false
    replication-factor = 1
    local-datacenter = ${CASSANDRA_DC}
  }
}

search {
  default = "elasticsearch"
  elasticsearch {
    addresses = ["http://wazuh-indexer:9200"]
  }
}

play.http.secret.key = ${THEHIVE_SECRET_KEY}
play.http.session.maxAge = 1d
